app:
  env: development
  port: 3000

database:
  mongoUri: mongodb://localhost:27017/jwt_dev

jwt:
  secret: dev_jwt_secret
  expiresIn: 86400

mail:
  host: sandbox.smtp.mailtrap.io
  port: 2525
  secure: false
  user: fe690ab25ca62c
  pass: f23edadc970bb1
  from: no-reply@dev.com
