app:
  env: production
  port: 80

database:
  mongoUri: mongodb+srv://elakiyavarshiniait_db_user:1234@mongoqueries.swdue9k.mongodb.net/?appName=MongoQueries

jwt:
  secret: prod_jwt_secret
  expiresIn: 86400

mail:
  host: smtp.prod.com
  port: 587
  user: prod_user
  pass: prod_pass
  from: no-reply@prod.com
